#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/1ab8128b-41f9-4f46-80c5-ace526e1a645 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool node1;
  bool node2;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#define spot_1 34
#define spot_2 21
void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
  pinMode(spot_1, INPUT);
  pinMode(spot_2, INPUT);
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  node1 = digitalRead(spot_1);
  node2 = digitalRead(spot_2);
  delay(50);
  
}




/*
  Since Node1 is READ_WRITE variable, onNode1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onNode1Change()  {
  // Add your code here to act upon Node1 change
}

/*
  Since Node2 is READ_WRITE variable, onNode2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onNode2Change()  {
  // Add your code here to act upon Node2 change
}