// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "412f0c6c-cc57-4ab1-af26-ef01a19db309";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onNode1Change();
void onNode2Change();

bool node1;
bool node2;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(node1, READWRITE, ON_CHANGE, onNode1Change);
  ArduinoCloud.addProperty(node2, READWRITE, ON_CHANGE, onNode2Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
